# Site settings
author: Alex Zdatny
title: Coding with Al
header-img: img/home-bg.png
email: alexzdatny@gmail.com
copyright_name: Alex Zdatny
description: > # this means to ignore newlines until "baseurl:"
  My journey as a web developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alcasinoroyale

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
